spring:
  application:
    name: LINKer-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
springdoc:
  api-docs:
    path: /api/docs/json
  swagger-ui:
    path: /api/docs/swagger-ui
