spring:
  application:
    name: LINKer-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  devtools:
    add-properties: true
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
springdoc:
  api-docs:
    path: /api/docs/json
  swagger-ui:
    path: /api/docs/swagger-ui
