spring:
  application:
    name: LINKer-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  devtools:
    add-properties: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
springdoc:
  api-docs:
    path: /api/docs/json
  swagger-ui:
    path: /api/docs/swagger-ui
